### ISSUE TITLE
[BUG] 네비게이션 바가 동시에 뜨는 현상

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-16#241]
<img width="561" alt="스크린샷 2019-12-06 오후 2 43 06" src="https://user-images.githubusercontent.com/22005861/70298980-da6b7f00-1836-11ea-9a78-948d078ed66a.png">

네비게이션바의 드롭다운에서 하나를 클릭하고 다른 네비게이션을 열면 열립니다.. 그 전꺼는 닫히는게 자연스러울것같아요

**Comment by dlatns0201** [comment]
감사합니다 성동동님~ 원래 bulma란 프레임 워크가 default로 가지고 있는 현상이네요. 개발자 도구로 따라가서 직접 수도 클래스를 직접 수정해서 버그 픽스했습니다
