### ISSUE TITLE
[BUG] 스터디 상세보기에서 태그 개수 안보임

### ISSUE THREAD

**Issue by doong-jo** [connect-foundation/2019-16#242]
스터디 상세보기에서 태그 개수는 있는데 내용이 없는 현상이 있습니다.

<img width="595" alt="스크린샷 2019-12-06 오후 2 47 54" src="https://user-images.githubusercontent.com/22005861/70299176-7e552a80-1837-11ea-8a00-416f525bfac0.png">

**Comment by dlatns0201** [comment]
> 스터디 상세보기에서 태그 개수는 있는데 내용이 없는 현상이 있습니다.
> 
> <img alt="스크린샷 2019-12-06 오후 2 47 54" width="595" src="https://user-images.githubusercontent.com/22005861/70299176-7e552a80-1837-11ea-8a00-416f525bfac0.png">

Validation을 못 하다보니 이런 현상이 생겼네요 ㅠㅠ
이제 validation을 수행하기 때문에 저런 현상은 이제 생기지 않을겁니다!
감사합니다 성동님!
