### ISSUE TITLE
[BUG] 로딩 과정

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-16#243]
### 테스트 환경

Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### 수행 절차

단순 로딩

### 오류 내용

`로딩 중 -> 데이터 로딩완료`
가 아니라
`로딩 중 -> 데이터가 업소용 -> 데이터 로딩완료`

### 기대 결과

데이터가 업소용이 뜨면 안좋을 거 같습니다!
훌륭한 사이트네요.

### 참고(스크린샷 등)
<img width="1552" alt="Screen Shot 2019-12-06 at 2 46 48 PM" src="https://user-images.githubusercontent.com/28642472/70299111-4c43c880-1837-11ea-8274-85839f556a4b.png">

**Comment by dlatns0201** [comment]
> ### 테스트 환경
> Chrome Version 78.0.3904.108 (Official Build) (64-bit)
> 
> ### 수행 절차
> 단순 로딩
> 
> ### 오류 내용
> `로딩 중 -> 데이터 로딩완료`
> 가 아니라
> `로딩 중 -> 데이터가 업소용 -> 데이터 로딩완료`
> 
> ### 기대 결과
> 데이터가 업소용이 뜨면 안좋을 거 같습니다!
> 훌륭한 사이트네요.
> 
> ### 참고(스크린샷 등)
> <img alt="Screen Shot 2019-12-06 at 2 46 48 PM" width="1552" src="https://user-images.githubusercontent.com/28642472/70299111-4c43c880-1837-11ea-8274-85839f556a4b.png">

감사합니다! 용호님이 발견해주신 이 이슈는 현재 커스텀 훅을 사용해 loading과 data load를 동기화 시켜 해결되어 close하겠습니다!
