### ISSUE TITLE
[Bug] 카테고리바에서 옵션이 2군대 펼쳐짐

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-16#247]
![image](https://user-images.githubusercontent.com/31912670/70299862-67afd300-1839-11ea-950b-908996819c13.png)

하나의 카테고리에서 옵션을 선택한후, 다른 카테고리에 hover할 경우 2개다 펼쳐짐

**Comment by dlatns0201** [comment]
해당 문제는 bulma 프레임워크의 default적인 문제로, 개발자 도구로 추적해 수도 클래스를 사용한 css 추가로 해결했습니다!

**Comment by dlatns0201** [comment]
> ![image](https://user-images.githubusercontent.com/31912670/70299862-67afd300-1839-11ea-950b-908996819c13.png)
> 
> 하나의 카테고리에서 옵션을 선택한후, 다른 카테고리에 hover할 경우 2개다 펼쳐짐

감사합니다! 종화님이 관심을 주신 덕분에
해당 문제는 bulma 프레임워크의 default적인 문제로, 개발자 도구로 추적해 수도 클래스를 사용한 css 추가로 해결했습니다!
