### ISSUE TITLE
[버그] 마우스아웃 이후에도 레이어가 계속 남아있음

### ISSUE THREAD

**Issue by crongro** [connect-foundation/2019-16#248]
상단 메뉴에 마우스오버 때 나오면  메뉴레이어가 
마우스아웃이 된 상태에서도 계속 노출됩니다.

**Comment by dlatns0201** [comment]
> 상단 메뉴에 마우스오버 때 나오면 메뉴레이어가
> 마우스아웃이 된 상태에서도 계속 노출됩니다.

크롱님 감사합니다!! 저 문제는 bulma 프레임워크의 navbar에서 default한 현상이였습니다 ㅠㅠ
그래서 개발자 도구를 사용하면서 추적한 결과 수도 클래스를 포함한 css 추가로 해결했습니다!
