### ISSUE TITLE
Nginx 설치 및 설정

### ISSUE THREAD

**Issue by soob-forest** [connect-foundation/2019-16#35]
- [x]  80번 포트 정적페이지 렌더링
- [x] 80:8000 포트 포워딩

**Comment by sejjj120** [comment]
- `/etc/nginx/conf.d/default` 파일에서 환경 설정
- 나중에 root 경로를 리액트 빌드 폴더로 변경
- /graphql 요청을 :8000/graphql 로 포워딩
